# Generated by Django 3.1.14 on 2022-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220215_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(to='users.Teacher'),
        ),
    ]
