# Generated by Django 3.1.14 on 2022-02-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_likecomment_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='value',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], default='LIKE', max_length=7),
        ),
        migrations.AddField(
            model_name='likepost',
            name='value',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], default='LIKE', max_length=7),
        ),
    ]
