# Generated by Django 3.1.14 on 2022-02-05 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20220201_1743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('main_task', models.TextField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.study_group')),
            ],
            options={
                'verbose_name': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.lesson')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='School_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('teachers', models.ManyToManyField(blank=True, related_name='School_Subject_teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Subject',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_mark', models.CharField(max_length=100, null=True)),
                ('mark', models.CharField(max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Mark_lesson', to='studies.lesson')),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.school_subject')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mark_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mark',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='school_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Lesson_school_subject', to='studies.school_subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
